name: deploy to self hosted runner

on:
  workflow_dispatch:

jobs:

  pull-and-deploy:
    runs-on: self-hosted
    env:
      USERNAME: ${{vars.DOCKER_USERNAME}}
      APP_NAME: ${{vars.APP_NAME}}
      GIT_SHA: ${{github.sha}}
    steps:
      - 
        name: checkout-code
        uses: actions/checkout@v6

      - 
        name: build the docker build 
        run: docker compose build --no-cache

      - 
        name: up the docker compose
        run: docker compose up -d 






