name: deploy to self hosted runner

on:
  workflow_run:

    workflows: ["build-and-push"]
    type: ["complete"]
    branches: ["main"]


jobs:

  pull-and-deploy:
    if: ${{github.event.workflow_run.conclusion=='success'}}
    runs-on: self-hosted
    env:
      USERNAME: ${{vars.DOCKER_USERNAME}}
      APP_NAME: ${{vars.APP_NAME}}
      GIT_SHA: ${{github.sha}}
    steps:
      - 
        name: checkout-code
        uses: actions/checkout@v6

      - 
        name: down
        run: docker compose down -v
      - 
        name: build the docker build 
        run: docker compose build --no-cache

      - 
        name: up the docker compose
        run: docker compose up -d 






